import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

/**
 * Ensures Supabase Storage URLs have the correct /public segment
 * This fixes URLs generated by getPublicUrl() which sometimes miss the /public part
 */
export function ensurePublicUrl(url: string): string {
  if (!url) return url
  
  // Check if URL is missing the /public segment
  if (url.includes('/storage/v1/object/documents/') && !url.includes('/storage/v1/object/public/documents/')) {
    return url.replace('/storage/v1/object/documents/', '/storage/v1/object/public/documents/')
  }
  
  return url
}

/**
 * Extracts the storage path from a Supabase Storage URL
 * Useful for converting public URLs back to storage paths
 */
export function extractStoragePath(url: string): string | null {
  if (!url) return null
  
  // Extract path from public URL
  const publicMatch = url.match(/\/storage\/v1\/object\/public\/documents\/(.+)/)
  if (publicMatch) {
    return decodeURIComponent(publicMatch[1])
  }
  
  // Extract path from non-public URL
  const privateMatch = url.match(/\/storage\/v1\/object\/documents\/(.+)/)
  if (privateMatch) {
    return decodeURIComponent(privateMatch[1])
  }
  
  return null
}
