-- Fix existing storage_path URLs to include /public segment
-- This script corrects URLs generated by Supabase Storage getPublicUrl() method

-- Update documents table: fix storage_path URLs
UPDATE public.documents 
SET storage_path = REPLACE(
  storage_path, 
  '/storage/v1/object/documents/', 
  '/storage/v1/object/public/documents/'
)
WHERE storage_path LIKE '%/storage/v1/object/documents/%'
  AND storage_path NOT LIKE '%/storage/v1/object/public/documents/%';

-- Show the results
SELECT 
  id,
  filename,
  storage_path,
  created_at
FROM public.documents 
WHERE storage_path LIKE '%/storage/v1/object/public/documents/%'
ORDER BY created_at DESC;

-- Count how many were updated
SELECT 
  COUNT(*) as total_documents,
  COUNT(CASE WHEN storage_path LIKE '%/storage/v1/object/public/documents/%' THEN 1 END) as correct_urls,
  COUNT(CASE WHEN storage_path LIKE '%/storage/v1/object/documents/%' THEN 1 END) as incorrect_urls
FROM public.documents;
